# Generated by Django 4.1.7 on 2023-02-18 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulefield',
            name='remote_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='remote', to='remote.remote'),
        ),
    ]
