# Generated by Django 4.0.9 on 2023-02-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0002_modulefield_remote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulefield',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='우선순위'),
            preserve_default=False,
        ),
    ]
