# Generated by Django 4.0.9 on 2023-02-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0003_modulefield_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulefield',
            name='remote_id',
        ),
        migrations.AlterField(
            model_name='remote',
            name='ip',
            field=models.CharField(max_length=20, unique=True, verbose_name='서버 아이피'),
        ),
    ]
