# Generated by Django 4.0.9 on 2023-02-20 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0004_remove_modulefield_remote_id_alter_remote_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulefield',
            name='remote_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='remote', to='remote.remote'),
        ),
    ]
